FROM node:20

WORKDIR /apps

COPY core/package*.json core/
COPY core/tsconfig.json core/

COPY game-service/package*.json game-service/
COPY game-service/tsconfig.json game-service/

WORKDIR /apps/core
RUN npm install

WORKDIR /apps/game-service
RUN npm install

WORKDIR /apps
COPY core/src core/src
COPY game-service/src game-service/src

WORKDIR /apps/core
RUN npm run build

WORKDIR /apps/game-service

EXPOSE 3000

CMD ["npm", "run", "dev"]
